### ISSUE TITLE
Does not open in OpenSUSE Leap 15.2

### ISSUE THREAD

**Issue by EagleScreen** [flathub/com.sweethome3d.Sweethome3d#3]
> flatpak run com.sweethome3d.Sweethome3d
Exception in thread "main" java.lang.ExceptionInInitializerError
	at javax.media.j3d.GraphicsConfigTemplate3D.isGraphicsConfigSupported(GraphicsConfigTemplate3D.java:348)
	at com.eteks.sweethome3d.j3d.Component3DManager.createGraphicsConfigurationTemplate3D(Unknown Source)
	at com.eteks.sweethome3d.j3d.Component3DManager.<init>(Unknown Source)
	at com.eteks.sweethome3d.j3d.Component3DManager.getInstance(Unknown Source)
	at com.eteks.sweethome3d.SweetHome3D.addComponent3DRenderingErrorObserver(Unknown Source)
	at com.eteks.sweethome3d.SweetHome3D.init(Unknown Source)
	at com.eteks.sweethome3d.SweetHome3D.main(Unknown Source)
Caused by: com.jogamp.opengl.GLException: Profiles [GL4bc, GL3bc, GL2, GLES1] not available on device null
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1039)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1050)
	at com.jogamp.opengl.GLProfile.getMaxFixedFunc(GLProfile.java:803)
	at javax.media.j3d.JoglPipeline.initialize(JoglPipeline.java:131)
	at javax.media.j3d.Pipeline.createPipeline(Pipeline.java:92)
	at javax.media.j3d.MasterControl.loadLibraries(MasterControl.java:858)
	at javax.media.j3d.VirtualUniverse.<clinit>(VirtualUniverse.java:267)
	... 7 more

**Comment by hadess** [comment]
Looks like a problem with your system:
> Caused by: com.jogamp.opengl.GLException: Profiles [GL4bc, GL3bc, GL2, GLES1] not available on device null

Make sure your system and all the Flatpak related software is up-to-date.

**Comment by EagleScreen** [comment]
So why the snap package is working?

**Comment by hadess** [comment]
> So why the snap package is working?

Because there's a problem with the GL drivers inside the Flatpak runtime itself, maybe? The fact that the snap package worked would have been useful information. So would the results of the actions I asked you to try and take...

**Comment by EagleScreen** [comment]
I have updated all my distribution packages, Opensuse 15.2 is in general a
very updated system, in fact it is a pre-release (beta). The flatpak
packages i have installed are these:
flatpak 1.6.2-lp152.1.2
libflatpak0 1.6.2-lp152.1.2
system-user-flatpak 1.6.2-lp152.1.2
typelib-1_0-Flatpak-1_0 1.6.2-lp152.1.2
xdg-dektop-portal 1.6.0-lp152.1.2

**Comment by hadess** [comment]
Please run `flatpak update -y`.

**Comment by EagleScreen** [comment]
~> flatpak update -y
Looking for updates…
Nothing to do.

**Comment by LeandroStanger** [comment]
Does not open in Endless OS

**Comment by hadess** [comment]
Somebody will need to debug that, because it works on all the machines I tested this on, as well as on machines using the NVidia driver.

**Comment by LeandroStanger** [comment]
![image](https://user-images.githubusercontent.com/26097419/79634859-87d69380-8143-11ea-9b75-b65c3d62ebfe.png)

**Comment by cypx** [comment]
Same error on Ubuntu 18.04, other flatpak (Firefox beta, Calibre, Shortwave....) running fine and SweetHome3D working using .deb or Snap

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at javax.media.j3d.GraphicsConfigTemplate3D.isGraphicsConfigSupported(GraphicsConfigTemplate3D.java:348)
        at com.eteks.sweethome3d.j3d.Component3DManager.createGraphicsConfigurationTemplate3D(Unknown Source)
        at com.eteks.sweethome3d.j3d.Component3DManager.<init>(Unknown Source)
        at com.eteks.sweethome3d.j3d.Component3DManager.getInstance(Unknown Source)
        at com.eteks.sweethome3d.SweetHome3D.addComponent3DRenderingErrorObserver(Unknown Source)
        at com.eteks.sweethome3d.SweetHome3D.init(Unknown Source)
        at com.eteks.sweethome3d.SweetHome3D.main(Unknown Source)
Caused by: com.jogamp.opengl.GLException: Profiles [GL4bc, GL3bc, GL2, GLES1] not available on device null
        at com.jogamp.opengl.GLProfile.get(GLProfile.java:1039)
        at com.jogamp.opengl.GLProfile.get(GLProfile.java:1050)
        at com.jogamp.opengl.GLProfile.getMaxFixedFunc(GLProfile.java:803)
        at javax.media.j3d.JoglPipeline.initialize(JoglPipeline.java:131)
        at javax.media.j3d.Pipeline.createPipeline(Pipeline.java:92)
        at javax.media.j3d.MasterControl.loadLibraries(MasterControl.java:858)
        at javax.media.j3d.VirtualUniverse.<clinit>(VirtualUniverse.java:267)
        ... 7 more
```

**Comment by mfd141** [comment]
I am having the same issue... hope this helps...

Fedora 31
Gnome 3.34-5
Intel® HD Graphics 530

$ **flatpak run com.sweethome3d.Sweethome3d**
Exception in thread "main" java.lang.ExceptionInInitializerError
	at javax.media.j3d.GraphicsConfigTemplate3D.isGraphicsConfigSupported(GraphicsConfigTemplate3D.java:348)
	at com.eteks.sweethome3d.j3d.Component3DManager.createGraphicsConfigurationTemplate3D(Unknown Source)
	at com.eteks.sweethome3d.j3d.Component3DManager.<init>(Unknown Source)
	at com.eteks.sweethome3d.j3d.Component3DManager.getInstance(Unknown Source)
	at com.eteks.sweethome3d.SweetHome3D.addComponent3DRenderingErrorObserver(Unknown Source)
	at com.eteks.sweethome3d.SweetHome3D.init(Unknown Source)
	at com.eteks.sweethome3d.SweetHome3D.main(Unknown Source)
Caused by: com.jogamp.opengl.GLException: Profiles [GL4bc, GL3bc, GL2, GLES1] not available on device null
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1039)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1050)
	at com.jogamp.opengl.GLProfile.getMaxFixedFunc(GLProfile.java:803)
	at javax.media.j3d.JoglPipeline.initialize(JoglPipeline.java:131)
	at javax.media.j3d.Pipeline.createPipeline(Pipeline.java:92)
	at javax.media.j3d.MasterControl.loadLibraries(MasterControl.java:858)
	at javax.media.j3d.VirtualUniverse.<clinit>(VirtualUniverse.java:267)
	... 7 more

$ **flatpak update -y**
Looking for updates…
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.
Nothing to do.

**Comment by mfd141** [comment]
It works on my other PC...

Fedora 31
KDE Plasma 5.17.5
GeForce GTX 1650

**Flatpak has the following installed...**
org.freedesktop.Platform.GL.nvidia-440-*
org.freedesktop.Platform.GL32.default
org.freedesktop.Platform.GL32.nvidia-440-*

> $ **flatpak run com.sweethome3d.Sweethome3d**
May 04, 2020 5:12:52 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Java 3D: implicit antialiasing enabled

> $ **flatpak update -y**
Looking for updates…
Nothing to do.

**Comment by hadess** [comment]
Test version at https://github.com/flathub/com.sweethome3d.Sweethome3d/pull/6
